@extends('layouts.master')
@section('title')
    Jabatan
@endsection
@section('content')
    @component('components.breadcrumb')
        @slot('li_1')
            Dasbor
        @endslot
        @slot('title')
            Jabatan
        @endslot
        @slot('li_end')
            Daftar
        @endslot
    @endcomponent
@endsection
@section('script')
    <script src="{{ URL::asset('/assets/js/app.min.js') }}"></script>
@endsection
